### PR TITLE
chore: update to stable V6

### PR DESCRIPTION
**Pull request by alsami**

### CODE REVIEW

**Comment by alistairjevans** [comment]
We've updated these packages to the new SDK style almost everywhere else....is it worth doing that here before we release?

**Comment by alsami** [comment]
> We've updated these packages to the new SDK style almost everywhere else....is it worth doing that here before we release?

Sure, can do, give me some minutes!

**Comment by alsami** [comment]
> We've updated these packages to the new SDK style almost everywhere else....is it worth doing that here before we release?

Good to go now. The folder "build" has actually been ignored b4. I removed it now and the pipeline seems to be working. I hope I haven't missed anything.

**Review by alistairjevans — APPROVED** [review]
Looks good 🎩

**Pull request merged**
