### PR TITLE
Switch to v 7.1.0 for this package 

### PR DESCRIPTION
**Pull request by alistairjevans**
(no breaking change, have just lifted the upper version cap)

### CODE REVIEW

**Comment by tillig** [comment]
I guess I missed it on mobile diff view - should the library rely on Autofac 7.0 by default, or at least a min of like 6.5? I think the tests got updated to depend on 7.0.

**Comment by alistairjevans** [comment]
I considered it, but I'm not sure there's a big reason to force users of this library to update to 7.0; I'm also not sure picking an arbitrary minimum is ideal either. This library is net472 only, so none of the new features in 7.0 will actually be available to them, and the library was previously only constrained to 6.0 and above; I want to get away from updating these old integration libraries on every release just to encourage people to stay with latest Autofac.

**Comment by alistairjevans** [comment]
I made the tests target 7 just because I wanted to verify compatibility with the new version.

I suppose there's an argument that we should only anchor against versions we run the tests against...

**Comment by tillig** [comment]
It may be worth making the minimum (if we're changing, releasing a new version) either:

- The latest Autofac at the time (7) to avoid any weirdness where folks will encounter that breaking `ILifetimeScope` change and not know what to do with it; OR
- The last Autofac 6 version (6.5.0) so the default installation experience pulls in the perf and features updates that happened over the course of the 6.0 release.

I mean, I don't think "arbitrary minimum" is really valuable, but there were some memory things in post 6.0 releases of core Autofac (ConcurrentBag stuff, IIRC) that it'd be nice to just skip folks past.

**Comment by alistairjevans** [comment]
Question then I suppose is "major version, and go to v7" or "minor version, and go to v6.5"?  Preference? I'd probably lean to the latter.

**Comment by tillig** [comment]
I'm fine with minor + 6.5, then if something comes up where someone tried upgrading to 7 and there's some "I can't figure out the right combo to make things work" issue we can go to 7.0 everywhere.

**Pull request merged**
