### PR TITLE
Allow multiple copies of the middleware on the same OWIN pipeline

### PR DESCRIPTION
**Pull request by huysentruitw**
Transparent fix for #1

### CODE REVIEW

**Comment by tillig** [comment]
I've asked for some clarification on #1 since multiple copies of the middleware doesn't imply multiple request lifetime scopes. Is the desired end result multiple middlewares + one request lifetime; or multiple middlewares + one request scope per middleware instance? Just to make sure this addresses the issue.

I like the solution, though - it's nice and tidy.

**Comment by tillig** [comment]
I'm going to pull this in and publish it to MyGet for testing prior to pushing to NuGet officially.

**Comment by alexmg** [comment]
Do you get a chance to test this @huysentruitw?

**Comment by huysentruitw** [comment]
Until now, I failed to create a NuGet package that ILmerges those assemblies. Maybe @brockallen is better placed to perform this test directly in IdentityServer?

**Comment by huysentruitw** [comment]
I would not merge this PR in the official library yet. While this fixes the setup of different copies of the assembly, there still is an issue with Autofac.Owin when you use it twice on the same pipeline:

```C#
app.Map("/a", appA => appA.UseWhateverA());
app.Map("/b", appB => appB.UseWhateverB());
```

Now, when both middlewares use Autofac.Owin while sharing the same Autofac.Owin library, only the first one gets registered correctly. This should be fixed IMO as it breaks the pluggable nature of OWIN and we don't want to drop Autofac as IoC container just yet :)

**Comment by tillig** [comment]
For reference (i.e., next time I'm looking in here) this discussion is continued over on issue #2.

**Pull request merged**
